#!/usr/bin/expect

#Usage to_nsx_step4 <host> <ssh user> <ssh password> <host_id> <filter_name>

set timeout 60
set hostid [lindex $argv 3]
set filter [lindex $argv 4]

spawn ssh [lindex $argv 1]@[lindex $argv 0]

expect "yes/no" {
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 2]\r" }
	} "*?assword" { send "[lindex $argv 2]\r" }

expect "> " { send "show dfw host $hostid filter $filter filterstats\r" }

expect "> " { send "exit" }
