#!/usr/bin/expect

#Usage to_nsx_step2 <host> <ssh user> <ssh password> <cluster_id>

set timeout 60

spawn ssh [lindex $argv 1]@[lindex $argv 0]

expect "yes/no" {
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 2]\r" }
	} "*?assword" { send "[lindex $argv 2]\r" }

expect "> " { send "show cluster [lindex $argv 3]\r" }

expect "> " { send "exit" }
